name = "avalon-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-11-01"
minify = true

[durable_objects]
bindings = [
  { name = "LOBBY", class_name = "LobbyDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDurableObject"]
